name: CI Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World from Github Actions with manual test!"
